#!/usr/bin/env python3
"""
generate_log.py
---------------
Runs inside GitHub Actions on every push to main.

Produces two outputs:
  docs/archive/YYYY-MM-DD/       — verbatim snapshots of every tracked source file
  docs/session-logs/YYYY-MM-DD.md — human-readable narrative for that day's work

If ANTHROPIC_API_KEY is present in the environment the narrative is generated by
Claude (claude-haiku). Without a key a structured-markdown fallback is written
instead — still useful, just not AI-narrated.
"""

import json
import os
import subprocess
import urllib.request
import urllib.error
from datetime import datetime, timezone
from pathlib import Path

# ── Source files to snapshot ───────────────────────────────────────────────────
SNAPSHOT_TARGETS = [
    ("index.html",                              "index.html"),
    ("main.js",                                 "main.js"),
    ("car-hero-selector/index.html",            "car-hero-selector-index.html"),
    ("car-hero-selector/src/main.js",           "car-hero-selector-main.js"),
    ("car-hero-selector/src/style.css",         "car-hero-selector-style.css"),
    ("car-hero-selector/vite.config.js",        "car-hero-selector-vite.config.js"),
    (".github/workflows/deploy.yml",            "workflows-deploy.yml"),
]

ZERO_SHA = "0" * 40

# ── Git helpers ────────────────────────────────────────────────────────────────

def git(*args):
    r = subprocess.run(["git"] + list(args), capture_output=True, text=True)
    return r.stdout.strip()


def commit_range():
    before = os.environ.get("GIT_BEFORE", "")
    after  = os.environ.get("GIT_AFTER", "HEAD")
    if before and before != ZERO_SHA:
        return before, after
    # First push / fallback: compare against parent of HEAD
    parent = git("rev-parse", "HEAD~1")
    return (parent or ZERO_SHA), after


def get_commits(before, after):
    fmt = "%h|||%s|||%ai|||%an"
    if before != ZERO_SHA:
        raw = git("log", f"{before}..{after}", f"--pretty=format:{fmt}")
    else:
        raw = git("log", after, "-12", f"--pretty=format:{fmt}")
    entries = []
    for line in raw.splitlines():
        parts = line.split("|||")
        if len(parts) >= 3:
            entries.append({
                "sha":    parts[0],
                "msg":    parts[1],
                "date":   parts[2][:10],
                "author": parts[3] if len(parts) > 3 else "",
            })
    return entries


def get_stat(before, after):
    if before != ZERO_SHA:
        return git("diff", f"{before}..{after}", "--stat")
    return git("diff", "HEAD~1..HEAD", "--stat")


def get_diff(before, after, max_chars=3800):
    if before != ZERO_SHA:
        d = git("diff", f"{before}..{after}", "--unified=2")
    else:
        d = git("diff", "HEAD~1..HEAD", "--unified=2")
    if len(d) > max_chars:
        d = d[:max_chars] + "\n\n…(truncated — see archive for full source)"
    return d

# ── Claude API ─────────────────────────────────────────────────────────────────

def call_claude(prompt: str, api_key: str) -> str | None:
    payload = json.dumps({
        "model": "claude-haiku-4-5-20251001",
        "max_tokens": 1400,
        "messages": [{"role": "user", "content": prompt}],
    }).encode()

    req = urllib.request.Request(
        "https://api.anthropic.com/v1/messages",
        data=payload, method="POST"
    )
    req.add_header("x-api-key", api_key)
    req.add_header("anthropic-version", "2023-06-01")
    req.add_header("content-type", "application/json")

    try:
        with urllib.request.urlopen(req, timeout=40) as resp:
            return json.loads(resp.read())["content"][0]["text"]
    except Exception as e:
        print(f"[session-log] Claude API call failed: {e}")
        return None


def build_narrative(commits, stat, diff, api_key) -> str:
    if not api_key:
        return _fallback_narrative(commits)

    commits_md = "\n".join(
        f"- `{c['sha']}` {c['msg']}  ({c['date']})" for c in commits
    )

    prompt = f"""You are documenting a software development session for a project called \
"Character Select" — an automotive car-selector web app with a rolodex carousel, \
SVG car silhouettes, real engine audio, manufacturer logos, and faction-based visual themes \
(BMW = Sophisticated, Porsche = Atmospheric Dominance, Toyota = Practical, Kia = Eco-Tech).

TODAY'S COMMITS:
{commits_md}

FILES CHANGED:
{stat}

PARTIAL DIFF:
{diff}

Write a work-log entry using EXACTLY this structure (use the headings verbatim):

## What Was Built
(4–7 bullet points in plain English — what was added or changed)

## What Worked Well
(2–4 bullet points — smooth wins, confirmed decisions, things that landed first try)

## Points of Friction
(1–4 bullet points — bugs fixed, things that needed multiple attempts, or write \
"None noted this session" if there were none)

## Session Summary
(2–4 sentences summing up the day's progress. Write as if briefing a collaborator \
who missed the session. Plain English, no jargon.)

Be concise. Do not repeat commit hashes in the body text."""

    result = call_claude(prompt, api_key)
    return result if result else _fallback_narrative(commits)


def _fallback_narrative(commits) -> str:
    lines = [
        "## What Was Built",
        "",
        *(f"- {c['msg']}" for c in commits),
        "",
        "## What Worked Well",
        "",
        "- *(Add ANTHROPIC_API_KEY to repo secrets for AI-generated analysis)*",
        "",
        "## Points of Friction",
        "",
        "- *(Add ANTHROPIC_API_KEY to repo secrets for AI-generated analysis)*",
        "",
        "## Session Summary",
        "",
        "*(Add ANTHROPIC_API_KEY to repo secrets for an AI-written summary.)*",
    ]
    return "\n".join(lines)

# ── Index updater ──────────────────────────────────────────────────────────────

def update_index(date_str: str):
    index = Path("docs/SESSIONS.md")
    link  = f"[{date_str}](session-logs/{date_str}.md)"

    if index.exists():
        content = index.read_text()
    else:
        content = (
            "# Character Select — Session Index\n\n"
            "Auto-generated. Each row links to the full work log for that session.\n\n"
            "| Date | Session Log |\n"
            "|------|-------------|\n"
        )

    if date_str not in content:
        lines = content.rstrip().splitlines()
        lines.append(f"| {date_str} | {link} |")
        index.write_text("\n".join(lines) + "\n")

# ── Main ───────────────────────────────────────────────────────────────────────

def main():
    date_str  = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    api_key   = os.environ.get("ANTHROPIC_API_KEY", "")

    # ── 1. Code archive ────────────────────────────────────────────────────────
    archive_dir = Path(f"docs/archive/{date_str}")
    archive_dir.mkdir(parents=True, exist_ok=True)

    archived = []
    for src, dest in SNAPSHOT_TARGETS:
        src_path = Path(src)
        if src_path.exists():
            (archive_dir / dest).write_text(src_path.read_text(errors="replace"))
            archived.append(f"- `{dest}`")

    # ── 2. Git data ────────────────────────────────────────────────────────────
    before, after = commit_range()
    commits = get_commits(before, after)
    stat    = get_stat(before, after)
    diff    = get_diff(before, after)

    if not commits:
        print("[session-log] No new commits found — skipping log generation.")
        return

    commits_md = "\n".join(
        f"- `{c['sha']}` {c['msg']}" for c in commits
    )

    # ── 3. AI narrative ────────────────────────────────────────────────────────
    narrative = build_narrative(commits, stat, diff, api_key)
    ai_label  = "Claude (Haiku)" if api_key else "auto-generated (no API key)"

    # ── 4. Build log document ──────────────────────────────────────────────────
    log_content = f"""# Session Log — {date_str}

> Auto-generated by `session-log` workflow · {timestamp}
> Narrative: {ai_label}

---

## Commits This Session

{commits_md}

## Files Changed

```
{stat if stat else "No stat available"}
```

---

{narrative}

---

## Code Archive

Verbatim snapshots of all source files for this session:

{chr(10).join(archived)}

📁 `docs/archive/{date_str}/`

"""

    # ── 5. Write (append if same-day log already exists) ──────────────────────
    log_dir  = Path("docs/session-logs")
    log_dir.mkdir(parents=True, exist_ok=True)
    log_path = log_dir / f"{date_str}.md"

    if log_path.exists():
        existing = log_path.read_text()
        log_path.write_text(existing.rstrip() + "\n\n---\n\n" + log_content)
        print(f"[session-log] Appended to {log_path}")
    else:
        log_path.write_text(log_content)
        print(f"[session-log] Created {log_path}")

    # ── 6. Update sessions index ───────────────────────────────────────────────
    update_index(date_str)
    print(f"[session-log] Archive written to {archive_dir}")


if __name__ == "__main__":
    main()
